version: "3.9"
services:
  caddy-lb:
    networks:
      - proxy
    image: caddy:2-alpine
    volumes:
      - ./caddy/data:/data
      - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"

networks:
  proxy:
